image: Visual Studio 2017
environment:
  access_token:
    secure: UBILkyBUiXnqv1n34QG2KQ3 / b8aBtpdFG78y5MWoG4 + ehwAGItWl2bkaSylpoDg2

install:
  - node --version
  - npm --version
  - npm install hexo --save
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-deployer-git --save
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"

build_script:
  - hexo generate

on_success:
  - hexo deploy